=== RuiOrey/master14/PDE/relatorio.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT documentos (documento+)>

<!ELEMENT documento (InfoGenerica,Texto,Referencias)>
<!ELEMENT InfoGenerica (autor+)>
<!ATTLIST InfoGenerica
	titulo CDATA #REQUIRED
	data_publicacao CDATA #REQUIRED
	local_publicacao CDATA #REQUIRED
	entidade_publica CDATA #REQUIRED
	id ID #REQUIRED>

<!ELEMENT Texto (#PCDATA |Capitulo|Seccao|Subseccao|p|Formatar)*>
<!ELEMENT Capitulo (#PCDATA |Seccao|Subseccao|p|Formatar)*>
<!ATTLIST Capitulo
	id ID #REQUIRED>
<!ELEMENT Seccao (#PCDATA |Subseccao|p|Formatar)*>
<!ATTLIST Seccao
	id ID #REQUIRED>
<!ELEMENT Subseccao (#PCDATA | p|Formatar)*>
<!ATTLIST Subseccao
	id ID #REQUIRED>
<!ELEMENT p (#PCDATA | Formatar)*>
<!ATTLIST p
	id ID #REQUIRED>

<!ELEMENT Formatar ( #PCDATA | b | strong | i | u | em | image | goto | reference)* >
<!ELEMENT b (#PCDATA | strong | i | u | em | image | goto | reference)*>
<!ELEMENT strong (#PCDATA | em | i | u | b | image | goto | reference)*>
<!ELEMENT i (#PCDATA | strong | em | u | b | image | goto | reference)*>
<!ELEMENT u (#PCDATA | strong | i | em | b | image | goto | reference)*>
<!ELEMENT em (#PCDATA | strong | i | u | b | image | goto | reference)*>
<!ELEMENT reference (#PCDATA | strong | i | u | b | image | goto | em)*>
<!ATTLIST reference
	id IDREF #REQUIRED>
<!ELEMENT goto (#PCDATA | strong | i | u | b | image | em | reference)*>
<!ATTLIST goto
	id IDREF #REQUIRED>
<!ELEMENT image (#PCDATA | strong | i | u | b | em | goto | reference)*>
<!ATTLIST image
	url CDATA #REQUIRED>

	

<!ELEMENT Referencias (Referencia+)>
<!ELEMENT Referencia (autor+)>
<!ATTLIST Referencia
	id ID #REQUIRED
	titulo CDATA #REQUIRED
	ano CDATA #REQUIRED
	url CDATA #IMPLIED>
<!ELEMENT autor EMPTY>
<!ATTLIST autor
	nome CDATA #IMPLIED>

=== RuiOrey/master14/PDE/relatorio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE documentos SYSTEM "relatorio.dtd" >
<documentos>
	<documento>
		<InfoGenerica 	titulo="Documento 1" data_publicacao="23/12/2013" local_publicacao="Porto" entidade_publica="Faculdade Ciencias" id="DOCX">
			<autor nome="Anonimo"/>
		</InfoGenerica>
		<Texto> Este é um texto de teste 
				<Capitulo >
					<p>Um paragrafo de teste num capitulo em<f><i>italico</i><b>, negrito </b><b><i> e negrito italico</i> </b></f> </p>
					<Seccao id="um">Aqui um seccao no capitulo
							<Subseccao id="umpontoum">
								E uma subsecçãoo..
							</Subseccao>
					</Seccao>
				</Capitulo>
				<Subseccao> Com conteudos mistos</Subseccao>
				<f>Aqui temos uma secção de formatação com texto em <i>italico</i>, <b>negrito</b>, <strong> carregado</strong>, <em>destacado</em> e <u>sublinhado</u></f>
				<f>Alem disso, temos uma <image url="imagem.jpg">imagem</image>, um <goto id="umpontoum">atalho para uma secção do documento</goto> e para uma <reference id="ref1">referencia na lista de referencias</reference> </f>
		</Texto>
		<Referencias>
			<Referencia id="ref1" titulo="Uma referencia" ano="1994" url="www.umareferencia.pt">
					<autor nome="Amilcar RJ"/>
					<autor nome="Rodolfo MA"/>
			</Referencia>
			<Referencia id="ref3" titulo="Outra referencia" ano="1995" url="www.umareferencia2.pt">
					<autor nome="Joana RJ"/>
			</Referencia>
		</Referencias>
	</documento>
</documentos>
